task_master/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taskmanager.urls", namespace="taskmanager")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taskmanager/urls.py
from django.urls import path

from taskmanager.views import (
    index, TaskListView,
    TaskDetailView, TaskCreateView,
    TaskUpdateView, TaskDeleteView,
    WorkerListView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list",
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list",
    ),
]

app_name = "taskmanager"

taskmanager/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(Position, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name} {self.position})"


class Task(models.Model):
    class Priorities(models.TextChoices):
        LOW = "low", "Low"
        MEDIUM = "medium", "Medium"
        HIGH = "high", "High"
        URGENT = "urgent", "Urgent"

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=10, choices=Priorities.choices)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(Worker, related_name="tasks")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return self.name

taskmanager/forms.py
from django import forms
from django.contrib.auth import get_user_model

from taskmanager.models import Task


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )
    assignee = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by assignee"
            }
        )
    )
    include_completed = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={'onclick': 'this.form.submit();'}),
        label="Include completed"
    )


class TaskForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={"type": "datetime-local"}
        )
    )
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )


    class Meta:
        model = Task
        fields = "__all__"

taskmanager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from taskmanager.forms import TaskSearchForm, TaskForm
from taskmanager.models import Task, Worker


@login_required
def index(request):
    total_tasks = Task.objects.count()
    completed_tasks = Task.objects.filter(is_completed=True).count()
    total_workers = Worker.objects.count()
    context = {
        "total_tasks": total_tasks,
        "completed_tasks": completed_tasks,
        "total_workers": total_workers,
    }
    return render(request, "taskmanager/index.html", context=context)


class TaskListView(LoginRequiredMixin, generic.ListView):
    paginate_by = 5

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        assignee = self.request.GET.get("assignee", "")
        include_completed = self.request.GET.get("include_completed")

        context["search_form"] = TaskSearchForm(
            initial={
                "name": name,
                "assignee": assignee,
                "include_completed": True if include_completed else False
            }
        )
        return context

    def get_queryset(self):
        queryset = Task.objects.prefetch_related("assignees")
        form = TaskSearchForm(self.request.GET)

        if not form.is_valid():
            return queryset

        name_contains = form.cleaned_data.get("name")
        assignee_contains = form.cleaned_data.get("assignee")
        include_completed = form.cleaned_data.get("include_completed")

        if name_contains:
            queryset = queryset.filter(name__icontains=name_contains)

        if assignee_contains:
            queryset = queryset.filter(assignees__username__icontains=assignee_contains)

        if not include_completed:
            queryset = queryset.filter(is_completed=False)

        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("taskmanager:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("taskmanager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("taskmanager:task-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    paginate_by = 5
    queryset = Worker.objects.select_related("position")
    success_url = reverse_lazy("taskmanager:worker-list")

templates/includes/head.html
{% load static %}

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Task Master</title>
<link rel="canonical" href="https://themesberg.com/product/admin-dashboard/volt-premium-bootstrap-5-dashboard">

<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

<!-- Volt CSS -->
<link type="text/css" href="{% static 'css/volt.css' %}" rel="stylesheet">

templates/includes/sidebar.html
{% load static %}

<nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
  <div class="sidebar-inner px-4 pt-3">
    <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
      <div class="d-flex align-items-center">
        <div class="d-block">
          <form method="post" action="{% url 'logout' %}?next={{ request.path }}">
            {% csrf_token %}
            <button class="btn btn-secondary btn-sm d-inline-flex align-items-center" type="submit">
              <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                   xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
              </svg>
              Sign Out
            </button>
          </form>
        </div>
      </div>
      <div class="collapse-close d-md-none">
        <a href="#sidebarMenu" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
           aria-expanded="true" aria-label="Toggle navigation">
          <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                  clip-rule="evenodd"></path>
          </svg>
        </a>
      </div>
    </div>
    <ul class="nav flex-column pt-3 pt-md-0">

      {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'taskmanager:index' %}" class="nav-link">
        <span class="sidebar-icon">
            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path>
              <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
            </svg>
          </span>
            <span class="sidebar-text">Dashboard</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'taskmanager:task-list' %}" class="nav-link">
          <span class="sidebar-icon">
            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                      d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2zM9 8H4v2h5V8z"
                      clip-rule="evenodd"></path>
              </svg>
          </span>
            <span class="sidebar-text">Tasks</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'taskmanager:worker-list' %}" class="nav-link">
          <span class="sidebar-icon">
            <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path
                  d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
              </path>
            </svg>
          </span>
            <span class="sidebar-text">Workers</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/taskmanager/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container vh-100"
       style="background-image: url({% static 'images/dashboard-bg.jpg' %}); background-size: cover;">
    <div class="row py-4">
      <div class="btn-toolbar mb-2 mb-md-0">
        <a href="{% url 'taskmanager:task-create' %}" class="btn btn-sm btn-gray-800 d-inline-flex align-items-center">
          <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"
               xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
          </svg>
          New Task
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-sm-6 col-xl-4 mb-4">
        <div class="card border-0 shadow">
          <div class="card-body">
            <div class="row d-block d-xl-flex align-items-center">
              <div
                  class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                <div class="icon-shape icon-shape-primary rounded me-4 me-sm-0">
                  <svg class="icon" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
                    </path>
                  </svg>
                </div>
              </div>
              <div class="col-12 col-xl-7 px-xl-0">
                <div class="d-none d-sm-block">
                  <h2 class="h6 text-gray-400 mb-0">Workers</h2>
                  <h3 class="fw-extrabold mb-2">{{ total_workers }}</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-6 col-xl-4 mb-4">
        <div class="card border-0 shadow">
          <div class="card-body">
            <div class="row d-block d-xl-flex align-items-center">
              <div
                  class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                <div class="icon-shape icon-shape-secondary rounded me-4 me-sm-0">
                  <svg class="icon" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z"
                          clip-rule="evenodd"></path>
                  </svg>
                </div>
              </div>
              <div class="col-12 col-xl-7 px-xl-0">
                <div class="d-none d-sm-block">
                  <h2 class="h6 text-gray-400 mb-0">Total tasks</h2>
                  <h3 class="fw-extrabold mb-2">{{ total_tasks }}</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-6 col-xl-4 mb-4">
        <div class="card border-0 shadow">
          <div class="card-body">
            <div class="row d-block d-xl-flex align-items-center">
              <div
                  class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                <div class="icon-shape icon-shape-tertiary rounded me-4 me-sm-0">
                  <svg class="icon" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M3 3a1 1 0 000 2v8a2 2 0 002 2h2.586l-1.293 1.293a1 1 0 101.414 1.414L10 15.414l2.293 2.293a1 1 0 001.414-1.414L12.414 15H15a2 2 0 002-2V5a1 1 0 100-2H3zm11.707 4.707a1 1 0 00-1.414-1.414L10 9.586 8.707 8.293a1 1 0 00-1.414 0l-2 2a1 1 0 101.414 1.414L8 10.414l1.293 1.293a1 1 0 001.414 0l4-4z"
                          clip-rule="evenodd"></path>
                  </svg>
                </div>
              </div>
              <div class="col-12 col-xl-7 px-xl-0">
                <div class="d-none d-sm-block">
                  <h2 class="h6 text-gray-400 mb-0"> Completed tasks</h2>
                  <h3 class="fw-extrabold mb-2">{{ completed_tasks }}</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/taskmanager/task_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <div class="py-4">
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
      <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
        <li class="breadcrumb-item">
          <a href="{% url 'taskmanager:index' %}">
            <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                 xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
              </path>
            </svg>
          </a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Delete task</li>
      </ol>
    </nav>
    <div class="d-flex justify-content-between w-100 flex-wrap">
      <div class="mb-3 mb-lg-0">
        <h1 class="h4">Delete task?</h1>
        <p>Are you sure you want to delete this task?</p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 mb-4">
      <div class="card border-0 shadow components-section">
        <div class="card-body">
          <a href="{% url "taskmanager:task-list" %}">
            <button class="btn btn-primary">Cancel</button>
          </a>
          <form action="" method="post" novalidate>
            {% csrf_token %}
            <input type="submit" value="Yes, delete" class="btn btn-danger"/>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/taskmanager/task_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="py-4 row">
    <div class="col-12 col-xl-8">
      <div class="card card-body border-0 shadow mb-4 mb-xl-0">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-1">
          <h2 class="h4 mb-4">{{ task.id }}. {{ task.name }} {% if task.is_completed %} (Completed) {% endif %}</h2>
          <div>
            <a class="btn btn-primary" href="{% url 'taskmanager:task-update' pk=task.id %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen"
                   viewBox="0 0 16 16">
                <path
                    d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708z"></path>
              </svg>
            </a>
            <a class="btn btn-outline-danger " href="{% url 'taskmanager:task-delete' pk=task.id %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash"
                   viewBox="0 0 16 16">
                <path
                    d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"></path>
                <path
                    d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"></path>
              </svg>
            </a>
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex align-items-center justify-content-between px-0 border-bottom">
            <div>
              <h2 class="h5 mb-1">Description:</h2>
              <p class="small pe-4">{{ task.description }}</p>
            </div>
          </li>
          <li class="list-group-item d-flex align-items-center justify-content-between px-0">
            <div>
              <h4 class="h6 mb-1">Assignees:</h4>
              {% for assignee in task.assignees.all %}
                <p class="small pe-4">{{ assignee.first_name }} {{ assignee.last_name }} ({{ assignee.username }})</p>
              {% endfor %}
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-12 col-xl-4">
      <div class="card border-0 shadow">
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between pt-3">
            <div>
              <div class="h6 mb-0 d-flex align-items-center">
                Priority:
              </div>
              <div class="small card-stats">
                {{ task.get_priority_display }}
                <svg class="icon icon-xs text-success" fill="currentColor" viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                        d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"
                        clip-rule="evenodd"></path>
                </svg>
              </div>
            </div>
          </div>
          <div class="d-flex align-items-center justify-content-between pt-3">
            <div>
              <div class="h6 mb-0 d-flex align-items-center">
                Type:
              </div>
              <div class="small card-stats">
                {{ task.task_type }}
              </div>
            </div>
          </div>
          <div class="d-flex align-items-center justify-content-between pt-3">
            <div>
              <div class="h6 mb-0 d-flex align-items-center">
                Deadline:
              </div>
              <div class="small card-stats">
                {{ task.deadline }}
              </div>
            </div>
          </div>
          <div class="d-flex align-items-center justify-content-between pt-3">
            <div>
              <div class="h6 mb-0 d-flex align-items-center">
                Creation date:
              </div>
              <div class="small card-stats">
                {{ task.created_at }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/taskmanager/task_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    <div class="d-block mb-4 mb-md-0">
      <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
          <li class="breadcrumb-item">
            <a href="{% url 'taskmanager:index' %}">
              <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                   xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                </path>
              </svg>
            </a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Tasks</li>
        </ol>
      </nav>
      <h2 class="h4">Tasks</h2>
    </div>
    <div class="btn-toolbar mb-2 mb-md-0">
      <a href="{% url 'taskmanager:task-create' %}" class="btn btn-sm btn-gray-800 d-inline-flex align-items-center">
        <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"
             xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
        </svg>
        New Task
      </a>
    </div>
  </div>
  <div class="table-settings mb-4">
    <form id="task-search-form" action="" method="get" class="form-inline">
      <div class="row align-items-center justify-content-between">

        <div class="col col-md-6 col-lg-4 col-xl-4">
          <div class="input-group me-2 me-lg-3 fmxw-400">
          <span class="input-group-text">
            <svg class="icon icon-xs" x-description="Heroicon name: solid/search" xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd"
                    d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                    clip-rule="evenodd"></path>
            </svg>
          </span>
            <input name="assignee" type="text" class="form-control" placeholder="Search by assignee"
                   value="{{ search_form.assignee.value }}">
          </div>
        </div>
        <div class="col">
          <div class="form-check">
            <input name="include_completed" class="form-check-input" type="checkbox"
                   onclick="this.form.submit();"
                {% if search_form.include_completed.value %} checked {% endif %}>
            <label class="form-check-label" for="defaultCheck10">
              Include completed
            </label>
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="card card-body border-0 shadow table-wrapper table-responsive">
    <table class="table table-hover">
      <thead>
      <tr>
        <th class="border-gray-200">#</th>
        <th class="border-gray-200">Name</th>
        <th class="border-gray-200">Priority</th>
        <th class="border-gray-200">Type</th>
        <th class="border-gray-200">Due Date</th>
        <th class="border-gray-200">Assignees</th>
        <th class="border-gray-200">Completed</th>
        <th class="border-gray-200">Action</th>
      </tr>
      </thead>
      <tbody>
      {% for task in task_list %}
        <tr>
          <td>
            {{ task.id }}
          </td>
          <td>
            <a href="{% url "taskmanager:task-detail" pk=task.id %}"><b>{{ task.name }}</b></a>
          </td>
          <td>
            {{ task.priority }}
          </td>
          <td>
            {{ task.task_type }}
          </td>
          <td>
            {{ task.deadline }}
          </td>
          <td>
            {{ task.assignees.count }}
            {% if task.assignees.count == 1 %}
              ({{ task.assignees.first.username }})
            {% endif %}
          </td>
          <td>
            <input class="form-check-input" type="checkbox" disabled
                {% if task.is_completed %} checked {% endif %}>
          </td>
          <td>
            <a style="color: red" href="{% url 'taskmanager:task-delete' pk=task.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}